"""empty message

Revision ID: 89a28b4add68
Revises: 
Create Date: 2020-07-31 14:21:52.770386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89a28b4add68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partner_user_device_bindings', sa.Column('gaia_user_device_unique_id', sa.String(length=63), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partner_user_device_bindings', 'gaia_user_device_unique_id')
    # ### end Alembic commands ###
