"""empty message

Revision ID: e8fc9255ff0f
Revises: 
Create Date: 2020-07-27 09:34:45.878019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8fc9255ff0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gaia_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('platform_user_id', sa.String(length=63), nullable=False),
    sa.Column('update_required', sa.Boolean(), nullable=False),
    sa.Column('immutable_identity', sa.String(length=255), nullable=False),
    sa.Column('json_data', sa.Text(), nullable=True),
    sa.Column('sso_id', sa.String(length=63), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_user_id', name='_platform_user_id_uc')
    )
    op.drop_index('_account_system_id_login_account_id_uc', table_name='gaia_login_detail')
    op.drop_table('gaia_login_detail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gaia_login_detail',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('account_system_id', mysql.VARCHAR(length=63), nullable=False),
    sa.Column('login_account_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('platform_user_id', mysql.VARCHAR(length=63), nullable=False),
    sa.Column('deleted_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('version_id', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('_account_system_id_login_account_id_uc', 'gaia_login_detail', ['account_system_id', 'login_account_id'], unique=True)
    op.drop_table('gaia_user')
    # ### end Alembic commands ###
